// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  /* tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  */
  // But you can create a sidebar manually

tutorialSidebar: [
     
     {
      type: 'category',
      label: 'Welcome to my repository',
      link: {
        type: 'generated-index',
        title: 'Welcome to my repository',
      },
      collapsible: true,
      collapsed: true, // Keeps the intro folder open by default
      items: [
        'intro/intro',
        'intro/intro-about-me', 
        'intro/intro-my-ai-journey',
      ],
    },
    
    {
      type: 'category',
      label: 'Portfolio',
      collapsible: true,
      collapsed: true, // Keeps the portfolio folder open by default
      items: [
        'portfolio/about-portfolio',
      {
          type: 'category',
          label: 'Vector search',
          items: [
            {
              type: 'doc',
              id: 'portfolio/vector-search/overview',
              label: 'Overview',
            },
            {
              type: 'doc',
              id: 'portfolio/vector-search/key-concepts',
              label: 'Key concepts',
            },
            {
              type: 'doc',
              id: 'portfolio/vector-search/how-it-works',
              label: 'How it works',
            },
            {
              type: 'doc',
              id: 'portfolio/vector-search/use-cases',
              label: 'Use cases',
            },
          ],
         },
        {
          type: 'category',
          label: 'Synonyms API',
          items: [
            {
              type: 'doc',
              id: 'portfolio/api-docs/overview',
              label: 'Overview ',
            },
            'portfolio/api-docs/authentication',
            'portfolio/api-docs/quickstart',

            {
              type: 'category',
              label: 'Endpoints',
              link: {
                type: 'doc',
                id: 'portfolio/api-docs/generated/synonyms-api/synonyms',  // no .mdx extension
              },
              items: [
                {
                  type: 'doc',
                  id: 'portfolio/api-docs/generated/synonyms-api/create-synonym',
                  label: 'Create a synonym entry',
                  className: 'api-method post',
                },
                {
                  type: 'doc',
                  id: 'portfolio/api-docs/generated/synonyms-api/list-synonyms',
                  label: 'List synonym entries',
                  className: 'api-method get',
                },
                {
                  type: 'doc',
                  id: 'portfolio/api-docs/generated/synonyms-api/get-synonym',
                  label: 'Get a synonym entry',
                  className: 'api-method get',
                },
                {
                  type: 'doc',
                  id: 'portfolio/api-docs/generated/synonyms-api/delete-synonym',
                  label: 'Delete a synonym entry',
                  className: 'api-method delete',
                },
              ],
            },



          ],
        },
        'portfolio/how-to-publish-target-zendesk',
        'portfolio/external-links',
      ],
    },
  ],
};

export default sidebars;
